# Bins and Stuff

In [140]:
%pip install iterstrat

ERROR: Could not find a version that satisfies the requirement iterstrat (from versions: none)
ERROR: No matching distribution found for iterstrat
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'iterstrat'

In [117]:
data_set_path = "/scratch-second/Preprocess_BraTS2023_SSA_Training/labels_UNN/"

Class presence : for each image and class, there is a binary vector if a class is present.

Foreground proportion bins: per class, percent of pixels that are foreground, binned 0 -

## The foreground bins

In [118]:
def analyze_labels(npy_files):
    # Check for presence of classes in each file
    # print("Numpy files shape:", npy_files[1:].sum(axis=(3)).shape)
    npy_files = npy_files[1:,:,:, 50 : 120].sum(axis=(3))
    label_presence = npy_files.any(axis=(1,2)).astype(int)
    # print("Label presence per class:\n", label_presence)

    # Calculate foreground proportion per class
    per_class_foreground = []
    for i in range(npy_files.shape[0]):
        foreground = npy_files[i].sum()
        # print(f"Foreground {foreground}")
        total = 192 * 224 * 70  # Assuming fixed dimensions
        proportion = foreground / total
        per_class_foreground.append(proportion)
    per_class_foreground = np.array(per_class_foreground)
    # print("Foreground proportion per class:\n", per_class_foreground)
    label_info = np.concatenate((per_class_foreground, label_presence))
    return label_info

In [119]:
test_npy = np.load('/scratch_net/ken/radjoe/BraTS_SSA/Validation/labels_UNN/BraTS-SSA-00015-000-lbl.npy')

In [120]:
analyze_labels(test_npy)

array([0.03909439, 0.05284764, 0.0198777 , 1.        , 1.        ,
       1.        ])

In [121]:
df = pd.DataFrame(columns=['Class_1_FG_Proportion', 'Class_2_FG_Proportion', 'Class_3_FG_Proportion', 'Class_1_Presence', 'Class_2_Presence', 'Class_3_Presence'])
for i in os.listdir(data_set_path):
    if i.endswith('.npy'):
        npy_file = np.load(os.path.join(data_set_path, i))
        label_info = analyze_labels(npy_file)
        # label_info = np.concatenate((np.array([i]), label_info))
        df.loc[i] = label_info

In [ ]:
# df.sort_index(inplace=True)

In [125]:
df

,Class_1_FG_Proportion,Class_2_FG_Proportion,Class_3_FG_Proportion,Class_1_Presence,Class_2_Presence,Class_3_Presence
BraTS-SSA-00002-000-lbl.npy,0.000176,0.046363,0.001410,1.0,1.0,1.0
BraTS-SSA-00007-000-lbl.npy,0.009876,0.057371,0.027264,1.0,1.0,1.0
BraTS-SSA-00008-000-lbl.npy,0.006422,0.015795,0.008642,1.0,1.0,1.0
BraTS-SSA-00010-000-lbl.npy,0.013697,0.023186,0.017360,1.0,1.0,1.0
BraTS-SSA-00011-000-lbl.npy,0.004790,0.040470,0.004884,1.0,1.0,1.0
BraTS-SSA-00012-000-lbl.npy,0.003087,0.033123,0.008727,1.0,1.0,1.0
BraTS-SSA-00014-000-lbl.npy,0.000008,0.025061,0.000942,1.0,1.0,1.0
BraTS-SSA-00015-000-lbl.npy,0.039094,0.052848,0.019878,1.0,1.0,1.0
BraTS-SSA-00025-000-lbl.npy,0.021706,0.007740,0.012741,1.0,1.0,1.0
BraTS-SSA-00026-000-lbl.npy,0.000640,0.034094,0.006452,1.0,1.0,1.0
BraTS-SSA-00028-000-lbl.npy,0.029494,0.009895,0.003078,1.0,1.0,1.0
BraTS-SSA-00037-000-lbl.npy,0.000000,0.003888,0.000000,0.0,1.0,0.0
BraTS-SSA-00041-000-lbl.npy,0.000000,0.012619,0.000351,0.0,1.0,1.0
BraTS-SSA-00044-000-lbl.npy,0.003170,0.039454,0.007999,1.0,1.0,1.0
BraTS-SSA-00046-000-lbl.npy,0.000000,0.020749,0.000221,0.0,1.0,1.0
BraTS-SSA-00047-000-lbl.npy,0.000704,0.002952,0.003013,1.0,1.0,1.0
BraTS-SSA-00049-000-lbl.npy,0.001097,0.016968,0.006482,1.0,1.0,1.0
BraTS-SSA-00050-000-lbl.npy,0.000037,0.028049,0.001100,1.0,1.0,1.0
BraTS-SSA-00051-000-lbl.npy,0.000039,0.013766,0.002061,1.0,1.0,1.0
BraTS-SSA-00055-000-lbl.npy,0.000563,0.044029,0.008636,1.0,1.0,1.0
BraTS-SSA-00056-000-lbl.npy,0.009393,0.021257,0.019571,1.0,1.0,1.0
BraTS-SSA-00057-000-lbl.npy,0.015739,0.052119,0.019528,1.0,1.0,1.0
BraTS-SSA-00068-000-lbl.npy,0.000869,0.007585,0.004289,1.0,1.0,1.0
BraTS-SSA-00074-000-lbl.npy,0.000895,0.011277,0.005139,1.0,1.0,1.0
BraTS-SSA-00076-000-lbl.npy,0.000621,0.055155,0.018695,1.0,1.0,1.0
BraTS-SSA-00078-000-lbl.npy,0.002681,0.054138,0.007421,1.0,1.0,1.0
BraTS-SSA-00080-000-lbl.npy,0.000098,0.014936,0.006658,1.0,1.0,1.0
BraTS-SSA-00081-000-lbl.npy,0.000297,0.081132,0.010306,1.0,1.0,1.0
BraTS-SSA-00092-000-lbl.npy,0.000019,0.002687,0.000050,1.0,1.0,1.0
BraTS-SSA-00093-000-lbl.npy,0.000000,0.037151,0.000000,0.0,1.0,0.0
BraTS-SSA-00095-000-lbl.npy,0.019084,0.022808,0.018372,1.0,1.0,1.0
BraTS-SSA-00096-000-lbl.npy,0.036316,0.019235,0.004277,1.0,1.0,1.0
BraTS-SSA-00097-000-lbl.npy,0.000385,0.036314,0.001246,1.0,1.0,1.0
BraTS-SSA-00110-000-lbl.npy,0.000000,0.031548,0.000346,0.0,1.0,1.0
BraTS-SSA-00112-000-lbl.npy,0.000004,0.002443,0.000670,1.0,1.0,1.0
BraTS-SSA-00113-000-lbl.npy,0.028914,0.048754,0.007115,1.0,1.0,1.0
BraTS-SSA-00115-000-lbl.npy,0.020199,0.013883,0.028574,1.0,1.0,1.0
BraTS-SSA-00116-000-lbl.npy,0.000348,0.084582,0.003917,1.0,1.0,1.0
BraTS-SSA-00117-000-lbl.npy,0.030209,0.034716,0.008468,1.0,1.0,1.0
BraTS-SSA-00119-000-lbl.npy,0.000072,0.018893,0.001999,1.0,1.0,1.0
BraTS-SSA-00120-000-lbl.npy,0.009413,0.028903,0.004046,1.0,1.0,1.0
BraTS-SSA-00121-000-lbl.npy,0.030069,0.007286,0.034660,1.0,1.0,1.0
BraTS-SSA-00122-000-lbl.npy,0.006289,0.029932,0.009162,1.0,1.0,1.0
BraTS-SSA-00127-000-lbl.npy,0.000658,0.004426,0.010395,1.0,1.0,1.0
BraTS-SSA-00131-000-lbl.npy,0.009229,0.036022,0.014169,1.0,1.0,1.0
BraTS-SSA-00133-000-lbl.npy,0.019896,0.024654,0.026199,1.0,1.0,1.0
BraTS-SSA-00135-000-lbl.npy,0.006441,0.041825,0.021228,1.0,1.0,1.0
BraTS-SSA-00141-000-lbl.npy,0.010296,0.024209,0.028978,1.0,1.0,1.0
BraTS-SSA-00144-000-lbl.npy,0.000231,0.005545,0.002427,1.0,1.0,1.0
BraTS-SSA-00146-000-lbl.npy,0.000000,0.000000,0.000000,0.0,0.0,0.0
BraTS-SSA-00150-000-lbl.npy,0.008124,0.055693,0.023020,1.0,1.0,1.0
BraTS-SSA-00152-000-lbl.npy,0.010801,0.027859,0.024124,1.0,1.0,1.0
BraTS-SSA-00161-000-lbl.npy,0.014192,0.012507,0.019064,1.0,1.0,1.0
BraTS-SSA-00202-000-lbl.npy,0.000699,0.010797,0.010219,1.0,1.0,1.0
BraTS-SSA-00213-000-lbl.npy,0.008175,0.046031,0.030812,1.0,1.0,1.0
BraTS-SSA-00215-000-lbl.npy,0.000000,0.000000,0.000000,0.0,0.0,0.0
BraTS-SSA-00220-000-lbl.npy,0.002060,0.050143,0.011449,1.0,1.0,1.0
BraTS-SSA-00221-000-lbl.npy,0.000002,0.028025,0.000577,1.0,1.0,1.0
BraTS-SSA-00223-000-lbl.npy,0.001856,0.057619,0.006347,1.0,1.0,1.0
BraTS-SSA-00230-000-lbl.npy,0.002004,0.057837,0.022573,1.0,1.0,1.0

In [ ]:
df.describe()

,Class_1_FG_Proportion,Class_2_FG_Proportion,Class_3_FG_Proportion,Class_1_Presence,Class_2_Presence,Class_3_Presence
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,0.007353,0.028806,0.010122,0.883333,0.966667,0.933333
std,0.010339,0.020007,0.009534,0.323732,0.181020,0.251549
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000157,0.012591,0.002046,1.000000,1.000000,1.000000
50%,0.001930,0.026460,0.007268,1.000000,1.000000,1.000000
75%,0.009981,0.042376,0.018453,1.000000,1.000000,1.000000
max,0.039094,0.084582,0.034660,1.000000,1.000000,1.000000

In [144]:
Y = df[['Class_1_Presence',	"Class_2_Presence", 	"Class_3_Presence"]].sum(1).to_numpy()
Y

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 1., 2., 3., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 1., 3., 3., 3., 2.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 0., 3.,
       3., 3., 3., 3., 0., 3., 3., 3., 3.])

In [145]:
X = df.index.to_list()

In [146]:
X

['BraTS-SSA-00002-000-lbl.npy',
 'BraTS-SSA-00007-000-lbl.npy',
 'BraTS-SSA-00008-000-lbl.npy',
 'BraTS-SSA-00010-000-lbl.npy',
 'BraTS-SSA-00011-000-lbl.npy',
 'BraTS-SSA-00012-000-lbl.npy',
 'BraTS-SSA-00014-000-lbl.npy',
 'BraTS-SSA-00015-000-lbl.npy',
 'BraTS-SSA-00025-000-lbl.npy',
 'BraTS-SSA-00026-000-lbl.npy',
 'BraTS-SSA-00028-000-lbl.npy',
 'BraTS-SSA-00037-000-lbl.npy',
 'BraTS-SSA-00041-000-lbl.npy',
 'BraTS-SSA-00044-000-lbl.npy',
 'BraTS-SSA-00046-000-lbl.npy',
 'BraTS-SSA-00047-000-lbl.npy',
 'BraTS-SSA-00049-000-lbl.npy',
 'BraTS-SSA-00050-000-lbl.npy',
 'BraTS-SSA-00051-000-lbl.npy',
 'BraTS-SSA-00055-000-lbl.npy',
 'BraTS-SSA-00056-000-lbl.npy',
 'BraTS-SSA-00057-000-lbl.npy',
 'BraTS-SSA-00068-000-lbl.npy',
 'BraTS-SSA-00074-000-lbl.npy',
 'BraTS-SSA-00076-000-lbl.npy',
 'BraTS-SSA-00078-000-lbl.npy',
 'BraTS-SSA-00080-000-lbl.npy',
 'BraTS-SSA-00081-000-lbl.npy',
 'BraTS-SSA-00092-000-lbl.npy',
 'BraTS-SSA-00093-000-lbl.npy',
 'BraTS-SSA-00095-000-lbl.npy',
 'BraTS-SSA-00096-000-lbl.npy',
 'BraTS-SSA-00097-000-lbl.npy',
 'BraTS-SSA-00110-000-lbl.npy',
 'BraTS-SSA-00112-000-lbl.npy',
 'BraTS-SSA-00113-000-lbl.npy',
 'BraTS-SSA-00115-000-lbl.npy',
 'BraTS-SSA-00116-000-lbl.npy',
 'BraTS-SSA-00117-000-lbl.npy',
 'BraTS-SSA-00119-000-lbl.npy',
 'BraTS-SSA-00120-000-lbl.npy',
 'BraTS-SSA-00121-000-lbl.npy',
 'BraTS-SSA-00122-000-lbl.npy',
 'BraTS-SSA-00127-000-lbl.npy',
 'BraTS-SSA-00131-000-lbl.npy',
 'BraTS-SSA-00133-000-lbl.npy',
 'BraTS-SSA-00135-000-lbl.npy',
 'BraTS-SSA-00141-000-lbl.npy',
 'BraTS-SSA-00144-000-lbl.npy',
 'BraTS-SSA-00146-000-lbl.npy',
 'BraTS-SSA-00150-000-lbl.npy',
 'BraTS-SSA-00152-000-lbl.npy',
 'BraTS-SSA-00161-000-lbl.npy',
 'BraTS-SSA-00202-000-lbl.npy',
 'BraTS-SSA-00213-000-lbl.npy',
 'BraTS-SSA-00215-000-lbl.npy',
 'BraTS-SSA-00220-000-lbl.npy',
 'BraTS-SSA-00221-000-lbl.npy',
 'BraTS-SSA-00223-000-lbl.npy',
 'BraTS-SSA-00230-000-lbl.npy']

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=50, stratify=Y, random_state=42)

In [156]:
def save_split(folder_path, label_path, save_path, train_files, cross_val):
    
    img_files = []

    for lbl in os.listdir(folder_path):
        for img in cross_val:
            print(img[:-8], lbl[:-8])
            if img[:-8] == lbl[:-8]:
                img_files.append(lbl)

    trainimg_files = []
    for lbl in os.listdir(folder_path):
        for img in train_files:
            print(img[:-8], lbl[:-8])
            if img[:-8] == lbl[:-8]:
                trainimg_files.append(lbl)

    val_savepath = f'{save_path}/Test/images_UNN'
    label_savepath = f'{save_path}/Test/labels_UNN'
    train_savepath = f'{save_path}/Validation/images_UNN'
    trainlabel_savepath = f'{save_path}/Validation/labels_UNN'
    os.makedirs(val_savepath, exist_ok=True)
    os.makedirs(label_savepath, exist_ok=True)
    os.makedirs(train_savepath, exist_ok=True)
    os.makedirs(trainlabel_savepath, exist_ok=True)

    for file in trainimg_files:
        shutil.copy(os.path.join(folder_path, file), val_savepath)

    for file in train_files:
        shutil.copy(os.path.join(label_path, file), label_savepath)

    for file in img_files:
        shutil.copy(os.path.join(folder_path, file), train_savepath)

    for file in cross_val:
        shutil.copy(os.path.join(label_path, file), trainlabel_savepath)

In [157]:
import shutil

In [158]:
folder_path = "/scratch-second/Preprocess_BraTS2023_SSA_Training/images_UNN/"
label_path = "/scratch-second/Preprocess_BraTS2023_SSA_Training/labels_UNN/"
save_path = "/scratch_net/ken/radjoe/BraTS_SSA"
save_split(folder_path, label_path, save_path, X_train, X_test)

BraTS-SSA-00213-000 BraTS-SSA-00116-000-st
BraTS-SSA-00057-000 BraTS-SSA-00116-000-st
BraTS-SSA-00074-000 BraTS-SSA-00116-000-st
BraTS-SSA-00015-000 BraTS-SSA-00116-000-st
BraTS-SSA-00110-000 BraTS-SSA-00116-000-st
BraTS-SSA-00120-000 BraTS-SSA-00116-000-st
BraTS-SSA-00230-000 BraTS-SSA-00116-000-st
BraTS-SSA-00044-000 BraTS-SSA-00116-000-st
BraTS-SSA-00221-000 BraTS-SSA-00116-000-st
BraTS-SSA-00135-000 BraTS-SSA-00116-000-st
BraTS-SSA-00068-000 BraTS-SSA-00116-000-st
BraTS-SSA-00037-000 BraTS-SSA-00116-000-st
BraTS-SSA-00095-000 BraTS-SSA-00116-000-st
BraTS-SSA-00051-000 BraTS-SSA-00116-000-st
BraTS-SSA-00131-000 BraTS-SSA-00116-000-st
BraTS-SSA-00025-000 BraTS-SSA-00116-000-st
BraTS-SSA-00122-000 BraTS-SSA-00116-000-st
BraTS-SSA-00127-000 BraTS-SSA-00116-000-st
BraTS-SSA-00047-000 BraTS-SSA-00116-000-st
BraTS-SSA-00215-000 BraTS-SSA-00116-000-st
BraTS-SSA-00097-000 BraTS-SSA-00116-000-st
BraTS-SSA-00078-000 BraTS-SSA-00116-000-st
BraTS-SSA-00010-000 BraTS-SSA-00116-000-st
BraTS-SSA-00008-000 BraTS-SSA-00116-000-st
BraTS-SSA-00081-000 BraTS-SSA-00116-000-st
BraTS-SSA-00161-000 BraTS-SSA-00116-000-st
BraTS-SSA-00055-000 BraTS-SSA-00116-000-st
BraTS-SSA-00220-000 BraTS-SSA-00116-000-st
BraTS-SSA-00076-000 BraTS-SSA-00116-000-st
BraTS-SSA-00028-000 BraTS-SSA-00116-000-st
BraTS-SSA-00056-000 BraTS-SSA-00116-000-st
BraTS-SSA-00133-000 BraTS-SSA-00116-000-st
BraTS-SSA-00050-000 BraTS-SSA-00116-000-st
BraTS-SSA-00026-000 BraTS-SSA-00116-000-st
BraTS-SSA-00150-000 BraTS-SSA-00116-000-st
BraTS-SSA-00202-000 BraTS-SSA-00116-000-st
BraTS-SSA-00011-000 BraTS-SSA-00116-000-st
BraTS-SSA-00116-000 BraTS-SSA-00116-000-st
BraTS-SSA-00014-000 BraTS-SSA-00116-000-st
BraTS-SSA-00007-000 BraTS-SSA-00116-000-st
BraTS-SSA-00144-000 BraTS-SSA-00116-000-st
BraTS-SSA-00112-000 BraTS-SSA-00116-000-st
BraTS-SSA-00117-000 BraTS-SSA-00116-000-st
BraTS-SSA-00121-000 BraTS-SSA-00116-000-st
BraTS-SSA-00092-000 BraTS-SSA-00116-000-st
BraTS-SSA-00141-000 BraTS-SSA-00116-000-st
BraTS-SSA-00080-000 BraTS-SSA-00116-000-st
BraTS-SSA-00041-000 BraTS-SSA-00116-000-st
BraTS-SSA-00146-000 BraTS-SSA-00116-000-st
BraTS-SSA-00093-000 BraTS-SSA-00116-000-st
BraTS-SSA-00213-000 BraTS-SSA-00115-000-st
BraTS-SSA-00057-000 BraTS-SSA-00115-000-st
BraTS-SSA-00074-000 BraTS-SSA-00115-000-st
BraTS-SSA-00015-000 BraTS-SSA-00115-000-st
BraTS-SSA-00110-000 BraTS-SSA-00115-000-st
BraTS-SSA-00120-000 BraTS-SSA-00115-000-st
BraTS-SSA-00230-000 BraTS-SSA-00115-000-st
BraTS-SSA-00044-000 BraTS-SSA-00115-000-st
BraTS-SSA-00221-000 BraTS-SSA-00115-000-st
BraTS-SSA-00135-000 BraTS-SSA-00115-000-st
BraTS-SSA-00068-000 BraTS-SSA-00115-000-st
BraTS-SSA-00037-000 BraTS-SSA-00115-000-st
BraTS-SSA-00095-000 BraTS-SSA-00115-000-st
BraTS-SSA-00051-000 BraTS-SSA-00115-000-st
BraTS-SSA-00131-000 BraTS-SSA-00115-000-st
BraTS-SSA-00025-000 BraTS-SSA-00115-000-st
BraTS-SSA-00122-000 BraTS-SSA-00115-000-st
BraTS-SSA-00127-000 BraTS-SSA-00115-000-st
BraTS-SSA-00047-000 BraTS-SSA-00115-000-st
BraTS-SSA-00215-000 BraTS-SSA-00115-000-st
BraTS-SSA-00097-000 BraTS-SSA-00115-000-st
BraTS-SSA-00078-000 BraTS-SSA-00115-000-st
BraTS-SSA-00010-000 BraTS-SSA-00115-000-st
BraTS-SSA-00008-000 BraTS-SSA-00115-000-st
BraTS-SSA-00081-000 BraTS-SSA-00115-000-st
BraTS-SSA-00161-000 BraTS-SSA-00115-000-st
BraTS-SSA-00055-000 BraTS-SSA-00115-000-st
BraTS-SSA-00220-000 BraTS-SSA-00115-000-st
BraTS-SSA-00076-000 BraTS-SSA-00115-000-st
BraTS-SSA-00028-000 BraTS-SSA-00115-000-st
BraTS-SSA-00056-000 BraTS-SSA-00115-000-st
BraTS-SSA-00133-000 BraTS-SSA-00115-000-st
BraTS-SSA-00050-000 BraTS-SSA-00115-000-st
BraTS-SSA-00026-000 BraTS-SSA-00115-000-st
BraTS-SSA-00150-000 BraTS-SSA-00115-000-st
BraTS-SSA-00202-000 BraTS-SSA-00115-000-st
BraTS-SSA-00011-000 BraTS-SSA-00115-000-st
BraTS-SSA-00116-000 BraTS-SSA-00115-000-st
BraTS-SSA-00014-000 BraTS-SSA-00115-000-st
BraTS-SSA-00007-000 BraTS-SSA-00115-000-st
BraTS-SSA-00144-000 BraTS-SSA-00115-000-st
BraTS-SSA-00112-000 BraTS-SSA-00115-000-st
BraTS-SSA-00117-000 BraTS-SSA-00115-000-st
BraTS-SSA-00121-000 BraTS-SSA-00115-000-st
BraTS-SSA-00092-000 BraTS-SSA-00115-000-st
BraTS-SSA-00141-000 BraTS-SSA-00115-000-st
BraTS-SSA-00080-000 BraTS-SSA-00115-000-st
BraTS-SSA-00041-000 BraTS-SSA-00115-000-st
BraTS-SSA-00146-000 BraTS-SSA-00115-000-st
BraTS-SSA-00093-000 BraTS-SSA-00115-000-st
BraTS-SSA-00213-000 BraTS-SSA-00051-000-st
BraTS-SSA-00057-000 BraTS-SSA-00051-000-st
BraTS-SSA-00074-000 BraTS-SSA-00051-000-st
BraTS-SSA-00015-000 BraTS-SSA-00051-000-st
BraTS-SSA-00110-000 BraTS-SSA-00051-000-st
BraTS-SSA-00120-000 BraTS-SSA-00051-000-st
BraTS-SSA-00230-000 BraTS-SSA-00051-000-st
BraTS-SSA-00044-000 BraTS-SSA-00051-000-st
BraTS-SSA-00221-000 BraTS-SSA-00051-000-st
BraTS-SSA-00135-000 BraTS-SSA-00051-000-st
BraTS-SSA-00068-000 BraTS-SSA-00051-000-st
BraTS-SSA-00037-000 BraTS-SSA-00051-000-st
BraTS-SSA-00095-000 BraTS-SSA-00051-000-st
BraTS-SSA-00051-000 BraTS-SSA-00051-000-st
BraTS-SSA-00131-000 BraTS-SSA-00051-000-st
BraTS-SSA-00025-000 BraTS-SSA-00051-000-st
BraTS-SSA-00122-000 BraTS-SSA-00051-000-st
BraTS-SSA-00127-000 BraTS-SSA-00051-000-st
BraTS-SSA-00047-000 BraTS-SSA-00051-000-st
BraTS-SSA-00215-000 BraTS-SSA-00051-000-st
BraTS-SSA-00097-000 BraTS-SSA-00051-000-st
BraTS-SSA-00078-000 BraTS-SSA-00051-000-st
BraTS-SSA-00010-000 BraTS-SSA-00051-000-st
BraTS-SSA-00008-000 BraTS-SSA-00051-000-st
BraTS-SSA-00081-000 BraTS-SSA-00051-000-st
BraTS-SSA-00161-000 BraTS-SSA-00051-000-st
BraTS-SSA-00055-000 BraTS-SSA-00051-000-st
BraTS-SSA-00220-000 BraTS-SSA-00051-000-st
BraTS-SSA-00076-000 BraTS-SSA-00051-000-st
BraTS-SSA-00028-000 BraTS-SSA-00051-000-st
BraTS-SSA-00056-000 BraTS-SSA-00051-000-st
BraTS-SSA-00133-000 BraTS-SSA-00051-000-st
BraTS-SSA-00050-000 BraTS-SSA-00051-000-st
BraTS-SSA-00026-000 BraTS-SSA-00051-000-st
BraTS-SSA-00150-000 BraTS-SSA-00051-000-st
BraTS-SSA-00202-000 BraTS-SSA-00051-000-st
BraTS-SSA-00011-000 BraTS-SSA-00051-000-st
BraTS-SSA-00116-000 BraTS-SSA-00051-000-st
BraTS-SSA-00014-000 BraTS-SSA-00051-000-st
BraTS-SSA-00007-000 BraTS-SSA-00051-000-st
BraTS-SSA-00144-000 BraTS-SSA-00051-000-st
BraTS-SSA-00112-000 BraTS-SSA-00051-000-st
BraTS-SSA-00117-000 BraTS-SSA-00051-000-st
BraTS-SSA-00121-000 BraTS-SSA-00051-000-st
BraTS-SSA-00092-000 BraTS-SSA-00051-000-st
BraTS-SSA-00141-000 BraTS-SSA-00051-000-st
BraTS-SSA-00080-000 BraTS-SSA-00051-000-st
BraTS-SSA-00041-000 BraTS-SSA-00051-000-st
BraTS-SSA-00146-000 BraTS-SSA-00051-000-st
BraTS-SSA-00093-000 BraTS-SSA-00051-000-st
BraTS-SSA-00213-000 BraTS-SSA-00096-000
BraTS-SSA-00057-000 BraTS-SSA-00096-000
BraTS-SSA-00074-000 BraTS-SSA-00096-000
BraTS-SSA-00015-000 BraTS-SSA-00096-000
BraTS-SSA-00110-000 BraTS-SSA-00096-000
BraTS-SSA-00120-000 BraTS-SSA-00096-000
BraTS-SSA-00230-000 BraTS-SSA-00096-000
BraTS-SSA-00044-000 BraTS-SSA-00096-000
BraTS-SSA-00221-000 BraTS-SSA-00096-000
BraTS-SSA-00135-000 BraTS-SSA-00096-000
BraTS-SSA-00068-000 BraTS-SSA-00096-000
BraTS-SSA-00037-000 BraTS-SSA-00096-000
BraTS-SSA-00095-000 BraTS-SSA-00096-000
BraTS-SSA-00051-000 BraTS-SSA-00096-000
BraTS-SSA-00131-000 BraTS-SSA-00096-000
BraTS-SSA-00025-000 BraTS-SSA-00096-000
BraTS-SSA-00122-000 BraTS-SSA-00096-000
BraTS-SSA-00127-000 BraTS-SSA-00096-000
BraTS-SSA-00047-000 BraTS-SSA-00096-000
BraTS-SSA-00215-000 BraTS-SSA-00096-000
BraTS-SSA-00097-000 BraTS-SSA-00096-000
BraTS-SSA-00078-000 BraTS-SSA-00096-000
BraTS-SSA-00010-000 BraTS-SSA-00096-000
BraTS-SSA-00008-000 BraTS-SSA-00096-000
BraTS-SSA-00081-000 BraTS-SSA-00096-000
BraTS-SSA-00161-000 BraTS-SSA-00096-000
BraTS-SSA-00055-000 BraTS-SSA-00096-000
BraTS-SSA-00220-000 BraTS-SSA-00096-000
BraTS-SSA-00076-000 BraTS-SSA-00096-000
BraTS-SSA-00028-000 BraTS-SSA-00096-000
BraTS-SSA-00056-000 BraTS-SSA-00096-000
BraTS-SSA-00133-000 BraTS-SSA-00096-000
BraTS-SSA-00050-000 BraTS-SSA-00096-000
BraTS-SSA-00026-000 BraTS-SSA-00096-000
BraTS-SSA-00150-000 BraTS-SSA-00096-000
BraTS-SSA-00202-000 BraTS-SSA-00096-000
BraTS-SSA-00011-000 BraTS-SSA-00096-000
BraTS-SSA-00116-000 BraTS-SSA-00096-000
BraTS-SSA-00014-000 BraTS-SSA-00096-000
BraTS-SSA-00007-000 BraTS-SSA-00096-000
BraTS-SSA-00144-000 BraTS-SSA-00096-000
BraTS-SSA-00112-000 BraTS-SSA-00096-000
BraTS-SSA-00117-000 BraTS-SSA-00096-000
BraTS-SSA-00121-000 BraTS-SSA-00096-000
BraTS-SSA-00092-000 BraTS-SSA-00096-000
BraTS-SSA-00141-000 BraTS-SSA-00096-000
BraTS-SSA-00080-000 BraTS-SSA-00096-000
BraTS-SSA-00041-000 BraTS-SSA-00096-000
BraTS-SSA-00146-000 BraTS-SSA-00096-000
BraTS-SSA-00093-000 BraTS-SSA-00096-000
BraTS-SSA-00213-000 BraTS-SSA-00223-000
BraTS-SSA-00057-000 BraTS-SSA-00223-000
BraTS-SSA-00074-000 BraTS-SSA-00223-000
BraTS-SSA-00015-000 BraTS-SSA-00223-000
BraTS-SSA-00110-000 BraTS-SSA-00223-000
BraTS-SSA-00120-000 BraTS-SSA-00223-000
BraTS-SSA-00230-000 BraTS-SSA-00223-000
BraTS-SSA-00044-000 BraTS-SSA-00223-000
BraTS-SSA-00221-000 BraTS-SSA-00223-000
BraTS-SSA-00135-000 BraTS-SSA-00223-000
BraTS-SSA-00068-000 BraTS-SSA-00223-000
BraTS-SSA-00037-000 BraTS-SSA-00223-000
BraTS-SSA-00095-000 BraTS-SSA-00223-000
BraTS-SSA-00051-000 BraTS-SSA-00223-000
BraTS-SSA-00131-000 BraTS-SSA-00223-000
BraTS-SSA-00025-000 BraTS-SSA-00223-000
BraTS-SSA-00122-000 BraTS-SSA-00223-000
BraTS-SSA-00127-000 BraTS-SSA-00223-000
BraTS-SSA-00047-000 BraTS-SSA-00223-000
BraTS-SSA-00215-000 BraTS-SSA-00223-000
BraTS-SSA-00097-000 BraTS-SSA-00223-000
BraTS-SSA-00078-000 BraTS-SSA-00223-000
BraTS-SSA-00010-000 BraTS-SSA-00223-000
BraTS-SSA-00008-000 BraTS-SSA-00223-000
BraTS-SSA-00081-000 BraTS-SSA-00223-000
BraTS-SSA-00161-000 BraTS-SSA-00223-000
BraTS-SSA-00055-000 BraTS-SSA-00223-000
BraTS-SSA-00220-000 BraTS-SSA-00223-000
BraTS-SSA-00076-000 BraTS-SSA-00223-000
BraTS-SSA-00028-000 BraTS-SSA-00223-000
BraTS-SSA-00056-000 BraTS-SSA-00223-000
BraTS-SSA-00133-000 BraTS-SSA-00223-000
BraTS-SSA-00050-000 BraTS-SSA-00223-000
BraTS-SSA-00026-000 BraTS-SSA-00223-000
BraTS-SSA-00150-000 BraTS-SSA-00223-000
BraTS-SSA-00202-000 BraTS-SSA-00223-000
BraTS-SSA-00011-000 BraTS-SSA-00223-000
BraTS-SSA-00116-000 BraTS-SSA-00223-000
BraTS-SSA-00014-000 BraTS-SSA-00223-000
BraTS-SSA-00007-000 BraTS-SSA-00223-000
BraTS-SSA-00144-000 BraTS-SSA-00223-000
BraTS-SSA-00112-000 BraTS-SSA-00223-000
BraTS-SSA-00117-000 BraTS-SSA-00223-000
BraTS-SSA-00121-000 BraTS-SSA-00223-000
BraTS-SSA-00092-000 BraTS-SSA-00223-000
BraTS-SSA-00141-000 BraTS-SSA-00223-000
BraTS-SSA-00080-000 BraTS-SSA-00223-000
BraTS-SSA-00041-000 BraTS-SSA-00223-000
BraTS-SSA-00146-000 BraTS-SSA-00223-000
BraTS-SSA-00093-000 BraTS-SSA-00223-000
BraTS-SSA-00213-000 BraTS-SSA-00152-000
BraTS-SSA-00057-000 BraTS-SSA-00152-000
BraTS-SSA-00074-000 BraTS-SSA-00152-000
BraTS-SSA-00015-000 BraTS-SSA-00152-000
BraTS-SSA-00110-000 BraTS-SSA-00152-000
BraTS-SSA-00120-000 BraTS-SSA-00152-000
BraTS-SSA-00230-000 BraTS-SSA-00152-000
BraTS-SSA-00044-000 BraTS-SSA-00152-000
BraTS-SSA-00221-000 BraTS-SSA-00152-000
BraTS-SSA-00135-000 BraTS-SSA-00152-000
BraTS-SSA-00068-000 BraTS-SSA-00152-000
BraTS-SSA-00037-000 BraTS-SSA-00152-000
BraTS-SSA-00095-000 BraTS-SSA-00152-000
BraTS-SSA-00051-000 BraTS-SSA-00152-000
BraTS-SSA-00131-000 BraTS-SSA-00152-000
BraTS-SSA-00025-000 BraTS-SSA-00152-000
BraTS-SSA-00122-000 BraTS-SSA-00152-000
BraTS-SSA-00127-000 BraTS-SSA-00152-000
BraTS-SSA-00047-000 BraTS-SSA-00152-000
BraTS-SSA-00215-000 BraTS-SSA-00152-000
BraTS-SSA-00097-000 BraTS-SSA-00152-000
BraTS-SSA-00078-000 BraTS-SSA-00152-000
BraTS-SSA-00010-000 BraTS-SSA-00152-000
BraTS-SSA-00008-000 BraTS-SSA-00152-000
BraTS-SSA-00081-000 BraTS-SSA-00152-000
BraTS-SSA-00161-000 BraTS-SSA-00152-000
BraTS-SSA-00055-000 BraTS-SSA-00152-000
BraTS-SSA-00220-000 BraTS-SSA-00152-000
BraTS-SSA-00076-000 BraTS-SSA-00152-000
BraTS-SSA-00028-000 BraTS-SSA-00152-000
BraTS-SSA-00056-000 BraTS-SSA-00152-000
BraTS-SSA-00133-000 BraTS-SSA-00152-000
BraTS-SSA-00050-000 BraTS-SSA-00152-000
BraTS-SSA-00026-000 BraTS-SSA-00152-000
BraTS-SSA-00150-000 BraTS-SSA-00152-000
BraTS-SSA-00202-000 BraTS-SSA-00152-000
BraTS-SSA-00011-000 BraTS-SSA-00152-000
BraTS-SSA-00116-000 BraTS-SSA-00152-000
BraTS-SSA-00014-000 BraTS-SSA-00152-000
BraTS-SSA-00007-000 BraTS-SSA-00152-000
BraTS-SSA-00144-000 BraTS-SSA-00152-000
BraTS-SSA-00112-000 BraTS-SSA-00152-000
BraTS-SSA-00117-000 BraTS-SSA-00152-000
BraTS-SSA-00121-000 BraTS-SSA-00152-000
BraTS-SSA-00092-000 BraTS-SSA-00152-000
BraTS-SSA-00141-000 BraTS-SSA-00152-000
BraTS-SSA-00080-000 BraTS-SSA-00152-000
BraTS-SSA-00041-000 BraTS-SSA-00152-000
BraTS-SSA-00146-000 BraTS-SSA-00152-000
BraTS-SSA-00093-000 BraTS-SSA-00152-000
BraTS-SSA-00213-000 BraTS-SSA-00074-000
BraTS-SSA-00057-000 BraTS-SSA-00074-000
BraTS-SSA-00074-000 BraTS-SSA-00074-000
BraTS-SSA-00015-000 BraTS-SSA-00074-000
BraTS-SSA-00110-000 BraTS-SSA-00074-000
BraTS-SSA-00120-000 BraTS-SSA-00074-000
BraTS-SSA-00230-000 BraTS-SSA-00074-000
BraTS-SSA-00044-000 BraTS-SSA-00074-000
BraTS-SSA-00221-000 BraTS-SSA-00074-000
BraTS-SSA-00135-000 BraTS-SSA-00074-000
BraTS-SSA-00068-000 BraTS-SSA-00074-000
BraTS-SSA-00037-000 BraTS-SSA-00074-000
BraTS-SSA-00095-000 BraTS-SSA-00074-000
BraTS-SSA-00051-000 BraTS-SSA-00074-000
BraTS-SSA-00131-000 BraTS-SSA-00074-000
BraTS-SSA-00025-000 BraTS-SSA-00074-000
BraTS-SSA-00122-000 BraTS-SSA-00074-000
BraTS-SSA-00127-000 BraTS-SSA-00074-000
BraTS-SSA-00047-000 BraTS-SSA-00074-000
BraTS-SSA-00215-000 BraTS-SSA-00074-000
BraTS-SSA-00097-000 BraTS-SSA-00074-000
BraTS-SSA-00078-000 BraTS-SSA-00074-000
BraTS-SSA-00010-000 BraTS-SSA-00074-000
BraTS-SSA-00008-000 BraTS-SSA-00074-000
BraTS-SSA-00081-000 BraTS-SSA-00074-000
BraTS-SSA-00161-000 BraTS-SSA-00074-000
BraTS-SSA-00055-000 BraTS-SSA-00074-000
BraTS-SSA-00220-000 BraTS-SSA-00074-000
BraTS-SSA-00076-000 BraTS-SSA-00074-000
BraTS-SSA-00028-000 BraTS-SSA-00074-000
BraTS-SSA-00056-000 BraTS-SSA-00074-000
BraTS-SSA-00133-000 BraTS-SSA-00074-000
BraTS-SSA-00050-000 BraTS-SSA-00074-000
BraTS-SSA-00026-000 BraTS-SSA-00074-000
BraTS-SSA-00150-000 BraTS-SSA-00074-000
BraTS-SSA-00202-000 BraTS-SSA-00074-000
BraTS-SSA-00011-000 BraTS-SSA-00074-000
BraTS-SSA-00116-000 BraTS-SSA-00074-000
BraTS-SSA-00014-000 BraTS-SSA-00074-000
BraTS-SSA-00007-000 BraTS-SSA-00074-000
BraTS-SSA-00144-000 BraTS-SSA-00074-000
BraTS-SSA-00112-000 BraTS-SSA-00074-000
BraTS-SSA-00117-000 BraTS-SSA-00074-000
BraTS-SSA-00121-000 BraTS-SSA-00074-000
BraTS-SSA-00092-000 BraTS-SSA-00074-000
BraTS-SSA-00141-000 BraTS-SSA-00074-000
BraTS-SSA-00080-000 BraTS-SSA-00074-000
BraTS-SSA-00041-000 BraTS-SSA-00074-000
BraTS-SSA-00146-000 BraTS-SSA-00074-000
BraTS-SSA-00093-000 BraTS-SSA-00074-000
BraTS-SSA-00213-000 BraTS-SSA-00215-000
BraTS-SSA-00057-000 BraTS-SSA-00215-000
BraTS-SSA-00074-000 BraTS-SSA-00215-000
BraTS-SSA-00015-000 BraTS-SSA-00215-000
BraTS-SSA-00110-000 BraTS-SSA-00215-000
BraTS-SSA-00120-000 BraTS-SSA-00215-000
BraTS-SSA-00230-000 BraTS-SSA-00215-000
BraTS-SSA-00044-000 BraTS-SSA-00215-000
BraTS-SSA-00221-000 BraTS-SSA-00215-000
BraTS-SSA-00135-000 BraTS-SSA-00215-000
BraTS-SSA-00068-000 BraTS-SSA-00215-000
BraTS-SSA-00037-000 BraTS-SSA-00215-000
BraTS-SSA-00095-000 BraTS-SSA-00215-000
BraTS-SSA-00051-000 BraTS-SSA-00215-000
BraTS-SSA-00131-000 BraTS-SSA-00215-000
BraTS-SSA-00025-000 BraTS-SSA-00215-000
BraTS-SSA-00122-000 BraTS-SSA-00215-000
BraTS-SSA-00127-000 BraTS-SSA-00215-000
BraTS-SSA-00047-000 BraTS-SSA-00215-000
BraTS-SSA-00215-000 BraTS-SSA-00215-000
BraTS-SSA-00097-000 BraTS-SSA-00215-000
BraTS-SSA-00078-000 BraTS-SSA-00215-000
BraTS-SSA-00010-000 BraTS-SSA-00215-000
BraTS-SSA-00008-000 BraTS-SSA-00215-000
BraTS-SSA-00081-000 BraTS-SSA-00215-000
BraTS-SSA-00161-000 BraTS-SSA-00215-000
BraTS-SSA-00055-000 BraTS-SSA-00215-000
BraTS-SSA-00220-000 BraTS-SSA-00215-000
BraTS-SSA-00076-000 BraTS-SSA-00215-000
BraTS-SSA-00028-000 BraTS-SSA-00215-000
BraTS-SSA-00056-000 BraTS-SSA-00215-000
BraTS-SSA-00133-000 BraTS-SSA-00215-000
BraTS-SSA-00050-000 BraTS-SSA-00215-000
BraTS-SSA-00026-000 BraTS-SSA-00215-000
BraTS-SSA-00150-000 BraTS-SSA-00215-000
BraTS-SSA-00202-000 BraTS-SSA-00215-000
BraTS-SSA-00011-000 BraTS-SSA-00215-000
BraTS-SSA-00116-000 BraTS-SSA-00215-000
BraTS-SSA-00014-000 BraTS-SSA-00215-000
BraTS-SSA-00007-000 BraTS-SSA-00215-000
BraTS-SSA-00144-000 BraTS-SSA-00215-000
BraTS-SSA-00112-000 BraTS-SSA-00215-000
BraTS-SSA-00117-000 BraTS-SSA-00215-000
BraTS-SSA-00121-000 BraTS-SSA-00215-000
BraTS-SSA-00092-000 BraTS-SSA-00215-000
BraTS-SSA-00141-000 BraTS-SSA-00215-000
BraTS-SSA-00080-000 BraTS-SSA-00215-000
BraTS-SSA-00041-000 BraTS-SSA-00215-000
BraTS-SSA-00146-000 BraTS-SSA-00215-000
BraTS-SSA-00093-000 BraTS-SSA-00215-000
BraTS-SSA-00213-000 BraTS-SSA-00076-000
BraTS-SSA-00057-000 BraTS-SSA-00076-000
BraTS-SSA-00074-000 BraTS-SSA-00076-000
BraTS-SSA-00015-000 BraTS-SSA-00076-000
BraTS-SSA-00110-000 BraTS-SSA-00076-000
BraTS-SSA-00120-000 BraTS-SSA-00076-000
BraTS-SSA-00230-000 BraTS-SSA-00076-000
BraTS-SSA-00044-000 BraTS-SSA-00076-000
BraTS-SSA-00221-000 BraTS-SSA-00076-000
BraTS-SSA-00135-000 BraTS-SSA-00076-000
BraTS-SSA-00068-000 BraTS-SSA-00076-000
BraTS-SSA-00037-000 BraTS-SSA-00076-000
BraTS-SSA-00095-000 BraTS-SSA-00076-000
BraTS-SSA-00051-000 BraTS-SSA-00076-000
BraTS-SSA-00131-000 BraTS-SSA-00076-000
BraTS-SSA-00025-000 BraTS-SSA-00076-000
BraTS-SSA-00122-000 BraTS-SSA-00076-000
BraTS-SSA-00127-000 BraTS-SSA-00076-000
BraTS-SSA-00047-000 BraTS-SSA-00076-000
BraTS-SSA-00215-000 BraTS-SSA-00076-000
BraTS-SSA-00097-000 BraTS-SSA-00076-000
BraTS-SSA-00078-000 BraTS-SSA-00076-000
BraTS-SSA-00010-000 BraTS-SSA-00076-000
BraTS-SSA-00008-000 BraTS-SSA-00076-000
BraTS-SSA-00081-000 BraTS-SSA-00076-000
BraTS-SSA-00161-000 BraTS-SSA-00076-000
BraTS-SSA-00055-000 BraTS-SSA-00076-000
BraTS-SSA-00220-000 BraTS-SSA-00076-000
BraTS-SSA-00076-000 BraTS-SSA-00076-000
BraTS-SSA-00028-000 BraTS-SSA-00076-000
BraTS-SSA-00056-000 BraTS-SSA-00076-000
BraTS-SSA-00133-000 BraTS-SSA-00076-000
BraTS-SSA-00050-000 BraTS-SSA-00076-000
BraTS-SSA-00026-000 BraTS-SSA-00076-000
BraTS-SSA-00150-000 BraTS-SSA-00076-000
BraTS-SSA-00202-000 BraTS-SSA-00076-000
BraTS-SSA-00011-000 BraTS-SSA-00076-000
BraTS-SSA-00116-000 BraTS-SSA-00076-000
BraTS-SSA-00014-000 BraTS-SSA-00076-000
BraTS-SSA-00007-000 BraTS-SSA-00076-000
BraTS-SSA-00144-000 BraTS-SSA-00076-000
BraTS-SSA-00112-000 BraTS-SSA-00076-000
BraTS-SSA-00117-000 BraTS-SSA-00076-000
BraTS-SSA-00121-000 BraTS-SSA-00076-000
BraTS-SSA-00092-000 BraTS-SSA-00076-000
BraTS-SSA-00141-000 BraTS-SSA-00076-000
BraTS-SSA-00080-000 BraTS-SSA-00076-000
BraTS-SSA-00041-000 BraTS-SSA-00076-000
BraTS-SSA-00146-000 BraTS-SSA-00076-000
BraTS-SSA-00093-000 BraTS-SSA-00076-000
BraTS-SSA-00213-000 BraTS-SSA-00057-000
BraTS-SSA-00057-000 BraTS-SSA-00057-000
BraTS-SSA-00074-000 BraTS-SSA-00057-000
BraTS-SSA-00015-000 BraTS-SSA-00057-000
BraTS-SSA-00110-000 BraTS-SSA-00057-000
BraTS-SSA-00120-000 BraTS-SSA-00057-000
BraTS-SSA-00230-000 BraTS-SSA-00057-000
BraTS-SSA-00044-000 BraTS-SSA-00057-000
BraTS-SSA-00221-000 BraTS-SSA-00057-000
BraTS-SSA-00135-000 BraTS-SSA-00057-000
BraTS-SSA-00068-000 BraTS-SSA-00057-000
BraTS-SSA-00037-000 BraTS-SSA-00057-000
BraTS-SSA-00095-000 BraTS-SSA-00057-000
BraTS-SSA-00051-000 BraTS-SSA-00057-000
BraTS-SSA-00131-000 BraTS-SSA-00057-000
BraTS-SSA-00025-000 BraTS-SSA-00057-000
BraTS-SSA-00122-000 BraTS-SSA-00057-000
BraTS-SSA-00127-000 BraTS-SSA-00057-000
BraTS-SSA-00047-000 BraTS-SSA-00057-000
BraTS-SSA-00215-000 BraTS-SSA-00057-000
BraTS-SSA-00097-000 BraTS-SSA-00057-000
BraTS-SSA-00078-000 BraTS-SSA-00057-000
BraTS-SSA-00010-000 BraTS-SSA-00057-000
BraTS-SSA-00008-000 BraTS-SSA-00057-000
BraTS-SSA-00081-000 BraTS-SSA-00057-000
BraTS-SSA-00161-000 BraTS-SSA-00057-000
BraTS-SSA-00055-000 BraTS-SSA-00057-000
BraTS-SSA-00220-000 BraTS-SSA-00057-000
BraTS-SSA-00076-000 BraTS-SSA-00057-000
BraTS-SSA-00028-000 BraTS-SSA-00057-000
BraTS-SSA-00056-000 BraTS-SSA-00057-000
BraTS-SSA-00133-000 BraTS-SSA-00057-000
BraTS-SSA-00050-000 BraTS-SSA-00057-000
BraTS-SSA-00026-000 BraTS-SSA-00057-000
BraTS-SSA-00150-000 BraTS-SSA-00057-000
BraTS-SSA-00202-000 BraTS-SSA-00057-000
BraTS-SSA-00011-000 BraTS-SSA-00057-000
BraTS-SSA-00116-000 BraTS-SSA-00057-000