# HOUSEKEEPING

In [1]:
import sys
import os
sys.path.append('/scratch_net/ken/radjoe/Projects/Experiments/SAMEXP/')

In [2]:
import albumentations as A
from albumentations.pytorch import ToTensorV2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats 
from scipy.stats import shapiro , kstest, mannwhitneyu, ttest_rel
import torch
from torch import nn
from datasets.datasets import MRIDataset, STAREDataset

from helper_func.analyis_helper import clean_df, plot_boxplots, visualize, generate_batch_views, visualize_views

## MAIN ANALYSIS

In [3]:

EXP_c10_path = "/scratch_net/ken/radjoe/Projects/Experiments/SAMEXP/results/BraTS_Valid/c10/EXP_boxes.csv"
EXP_c20_path = "/scratch_net/ken/radjoe/Projects/Experiments/SAMEXP/results/BraTS_Valid/c20/EXP_boxes.csv"
EXP_c30_path = "/scratch_net/ken/radjoe/Projects/Experiments/SAMEXP/results/BraTS_Valid/c30/EXP_boxes.csv"
EXP_c40_path =  "/scratch_net/ken/radjoe/Projects/Experiments/SAMEXP/results/BraTS_Valid/c40/EXP_boxes.csv"

In [4]:

EXP_c10_df = pd.read_csv(EXP_c10_path)
EXP_c20_df = pd.read_csv(EXP_c20_path)
EXP_c30_df = pd.read_csv(EXP_c30_path)
EXP_c40_df = pd.read_csv(EXP_c40_path)

In [5]:
EXP_c10_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,BraTS-GLI-00000-000.npy,0.010556,0.015993,0.602743,139.153351,108.286659,82.773178,0.909865,0.728498,0.964590,0.005309,0.008085,0.438317
1,1,BraTS-GLI-00005-000.npy,0.030990,0.065951,0.453835,154.434448,124.020409,68.876701,0.962914,0.821089,0.735432,0.015749,0.034355,0.328176
2,2,BraTS-GLI-00006-000.npy,0.031815,0.061129,0.514014,154.227112,93.557472,105.123734,0.971066,0.671592,0.831027,0.016173,0.032022,0.372078
3,3,BraTS-GLI-00008-001.npy,NaN,0.000000,0.000000,NaN,139.692520,100.942062,NaN,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
EXP_c20_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,BraTS-GLI-00000-000.npy,0.033173,0.025439,0.707303,131.886322,106.475349,58.721802,0.945391,0.693440,0.985732,0.016883,0.012957,0.551521
1,1,BraTS-GLI-00005-000.npy,0.190127,0.120371,0.628376,143.989014,123.474693,51.738281,0.969322,0.773266,0.808586,0.105401,0.065265,0.513853
2,2,BraTS-GLI-00006-000.npy,0.278606,0.112577,0.742200,107.093414,89.466476,85.078781,0.994276,0.554126,0.890427,0.162000,0.062653,0.636280
3,3,BraTS-GLI-00008-001.npy,NaN,0.000000,0.000000,NaN,150.264435,99.168289,NaN,0.000000,0.000000,0.000000,0.000000,0.000000

In [7]:
EXP_c30_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,BraTS-GLI-00000-000.npy,0.038959,0.019398,0.733249,142.302490,113.322548,55.982140,0.933379,0.727407,0.986160,0.019895,0.009830,0.583583
1,1,BraTS-GLI-00005-000.npy,0.788056,0.075390,0.705194,51.567413,120.557037,49.979996,0.984248,0.876456,0.798273,0.657080,0.039389,0.631554
2,2,BraTS-GLI-00006-000.npy,0.423281,0.088757,0.772921,109.290665,112.182884,100.493782,0.996667,0.675931,0.879764,0.268698,0.047497,0.689218
3,3,BraTS-GLI-00008-001.npy,NaN,0.000000,0.271938,NaN,140.548920,109.644653,NaN,0.000000,0.720512,0.000000,0.000000,0.167597

In [8]:
EXP_c40_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,BraTS-GLI-00000-000.npy,0.059061,0.045894,0.855291,131.342285,100.960388,3.741657,0.917022,0.602213,0.989643,0.030513,0.023856,0.753057
1,1,BraTS-GLI-00005-000.npy,0.051404,0.184035,0.831921,136.238754,113.481277,9.949874,0.991814,0.742683,0.881026,0.026386,0.105030,0.788001
2,2,BraTS-GLI-00006-000.npy,0.165220,0.329909,0.887856,123.340988,91.918442,3.741657,0.996315,0.632595,0.913755,0.090079,0.223141,0.863385
3,3,BraTS-GLI-00008-001.npy,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN

In [10]:
EXP_clatest_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,BraTS-GLI-00000-000.npy,0.039080,0.019729,0.924601,124.199814,83.336670,1.414214,0.975038,0.879869,0.973725,0.019939,0.009976,0.880196
1,1,BraTS-GLI-00005-000.npy,0.057702,0.115704,0.898252,143.958328,76.026314,1.732051,0.982139,0.976362,0.891004,0.029724,0.061496,0.905620
2,2,BraTS-GLI-00006-000.npy,0.078172,0.110155,0.921268,128.226364,88.141930,1.000000,0.997452,0.987959,0.890389,0.040680,0.058330,0.954367
3,3,BraTS-GLI-00008-001.npy,NaN,0.038560,0.850372,NaN,97.398148,105.893585,NaN,0.064415,0.846461,0.000000,0.027515,0.854318